### ISSUE TITLE
STT as a Websocket (server side)

### ISSUE THREAD

**Issue by ahmed-troido** [KoljaB/RealtimeSTT#105]
I want to create the STT to act as server(To receive audio chunks and send back the full sentence to the client) using websocket and I found this example here:
[Sockect Example](https://github.com/KoljaB/RealtimeSTT/tree/master/example_webserver)

**How do I handle multiple clients at the same time?**
```For example client_1 and client_2 are connected and sending audio chunks at the same time so maybe we will face a collision problem here between the chunks of both, because I'm using the same method call feed_audio to feed the STT```

**Comment by KoljaB** [comment]
You'd need to queue the requests or start multiple RealtimeSTT instances. The underlying model (whisper) does not allow concurrent requests.
