### ISSUE TITLE
Is there a way to use it with a web app instead of native mic

### ISSUE THREAD

**Issue by abhishek-tg** [KoljaB/RealtimeSTT#12]
I was just trying to create a web app and wanted to modify this to use it to a web app like from JS. Is there a sample?

**Comment by KoljaB** [comment]
Currently only a [python](https://github.com/KoljaB/RealtimeSTT/tree/master/example_webserver) webclient sample.

**Comment by KoljaB** [comment]
Just realized that the current client does not record and send chunks.  

This is a useful feature and very needed. Need to think about how to integrate taking chunks into the API, will then provide a JS client.

**Comment by abhishek-tg** [comment]
Also it uses pyaudio input stream which will be changed to socket queue or something.

**Comment by KoljaB** [comment]
Availble now, please check [this example](https://github.com/KoljaB/RealtimeSTT/tree/master/example_browserclient) with the new v0.1.8 Version.

**Comment by KoljaB** [comment]
Depends on what you want to achieve. Handling multiple user inputs in parallel will be not easy, especially if you want to also realtime transcribe. First you'd need to change RealtimeSTT for this, the processing is not designed for multiple incoming audio chunk feeds. You would need to create multiple worker threads for every feed. While a user talks the server needs to do voice activity detection and transcription, which needs VRAM and causes load on GPU. So either you'd need to load balance VAD and transcription somehow or you'd need big amounts of VRAM and GPU power on the server to handle that.
