### ISSUE TITLE
Languages supported

### ISSUE THREAD

**Issue by Zireael07** [KoljaB/RealtimeSTT#13]
Which languages are supported?

**Comment by skripnik** [comment]
Here you can find all the language codes that Whisper supports:
https://github.com/openai/whisper/blob/main/whisper/tokenizer.py

**Comment by skripnik** [comment]
It would be nice to mention allowed language values in [README.md](https://github.com/KoljaB/RealtimeSTT/blob/master/README.md). Something like this:

- **language** (str, default=""): Language code for transcription. If left empty, the model will try to auto-detect the language. Supported language codes are listed in [Whisper Tokenizer library](https://github.com/openai/whisper/blob/main/whisper/tokenizer.py).
