### ISSUE TITLE
Bump Porcupine version to at least 2.0 support mac/amd64

### ISSUE THREAD

**Issue by Npahlfer** [KoljaB/RealtimeSTT#15]
Porcupine 1.9 only supports mac x86_64 arch, but 2.0 adds support for mac amd64.
The downside is that it adds the requirement for an `access_key` in the `pvporcupine.create()` method.
Thoughts?

**Comment by KoljaB** [comment]
The v1.9.5 used is the last where Pvporcupine offers free usage. Changing this would force everybody to create a chargeable account (and toss a coin for longer usage). I feel that would put people off.
If you want this, pls just change it in the code.
