### ISSUE TITLE
Can the model's automatic translation to the specified language be disabled?

### ISSUE THREAD

**Issue by Pixellevel** [KoljaB/RealtimeSTT#150]
from RealtimeSTT import AudioToTextRecorder
import pyperclip  

def process_text(text):
    pyperclip.copy(text)  

if __name__ == '__main__':
    print("Wait until it says 'speak now'")
    recorder = AudioToTextRecorder(
        model="large-v2",  
        language="ja",
        spinner=False,  
        silero_deactivity_detection=True,  
        early_transcription_on_silence = 100,
        post_speech_silence_duration=0.2,  
    )

    while True:
        recorder.text(process_text)  

The above is the content of my script. When I use it, regardless of whether I use the large or medium model, after setting the language to Japanese, when it hears other languages, it automatically translates them into Japanese instead of directly recognizing them as Japanese. If I click the speaker icon in the bottom right corner of the Windows desktop to adjust the volume, and it makes a sound in a quiet environment, it will output: ご視聴ありがとうございました. (Thank you for watching.)

**Comment by KoljaB** [comment]
Can't be disable, this is inherent to the OpenAI Whisper model we use for transcription. Only way is to leave language blank, then Whisper would autodetect the language.

**Comment by homelab-00** [comment]
>If I click the speaker icon in the bottom right corner of the Windows desktop to adjust the volume, and it makes a sound in a quiet environment, it will output: ご視聴ありがとうございました. (Thank you for watching.)

That's probably a hallucination of the whisper model.

>When I use it, regardless of whether I use the large or medium model, after setting the language to Japanese, when it hears other languages, it automatically translates them into Japanese instead of directly recognizing them as Japanese. 

Do you mean that it auto-translates _other_ languages in Japanese? What do you mean by 'recognizing them as Japanese' - if they're different languages how can they be recognized as Japanese?

**Comment by Pixellevel** [comment]
If I set the language to Japanese, then if I speak Chinese, it will recognize my Chinese and then translate the meaning of the Chinese into Japanese.
When I previously said "recognizing them as Japanese" what I meant was that I hope it functions as if it is a standalone Japanese model.Regardless of what it hears, it should interpret the sounds as if they are Japanese pronunciations and recognize them as such.        
However, as previously mentioned, it cannot work this way; this is inherent to the model.

**Comment by KoljaB** [comment]
"Thank you for watching." is a common Whisper hallucination when trying to transcribe "silent audio" without speech. This will occur with RealtimeSTT if the voice activity detection falsely recognizes noises as speech.

To mitigate this try setting webrtc_sensitivity to 3 and silero_sensitivity to lower values like 0.1 or even lower. This will make the VAD models more aggressive about filtering out non-speech, raising tolerance towards noises.

**Comment by homelab-00** [comment]
> If I set the language to Japanese, then if I speak Chinese, it will recognize my Chinese and then translate the meaning of the Chinese into Japanese. When I previously said "recognizing them as Japanese" what I meant was that I hope it functions as if it is a standalone Japanese model.Regardless of what it hears, it should interpret the sounds as if they are Japanese pronunciations and recognize them as such. However, as previously mentioned, it cannot work this way; this is inherent to the model.

From my experience, setting the language of the model to Greek doesn't mean it auto-translates non-Greek speech to Greek. I can throw a mix of some English in there and it transcribes it correctly. Also bear in mind that Greek and English use a different alphabet [(α,β,γ,δ,...) vs (a,b,c,d,...)] and it doesn't have a problem with that either - meaning it uses the correct alphabet for the detected language.

I have encountered auto-translation only in the case of non-English speech being auto-translated into English - even if I've set the language to Greek. But only in the 'distil' models (like [Systran/faster-distil-whisper-large-v3](https://huggingface.co/Systran/faster-distil-whisper-large-v3)).

However I don't think it's possible to force the model to parse all sounds as pronunciations in a specific language, regardless of what the language parameter is set to - as evidenced by the Greek example I gave.

**Comment by Pixellevel** [comment]
> > If I set the language to Japanese, then if I speak Chinese, it will recognize my Chinese and then translate the meaning of the Chinese into Japanese. When I previously said "recognizing them as Japanese" what I meant was that I hope it functions as if it is a standalone Japanese model.Regardless of what it hears, it should interpret the sounds as if they are Japanese pronunciations and recognize them as such. However, as previously mentioned, it cannot work this way; this is inherent to the model.
> 
> From my experience, setting the language of the model to Greek doesn't mean it auto-translates non-Greek speech to Greek. I can throw a mix of some English in there and it transcribes it correctly. Also bear in mind that Greek and English use a different alphabet [(α,β,γ,δ,...) vs (a,b,c,d,...)] and it doesn't have a problem with that either - meaning it uses the correct alphabet for the detected language.
> 
> I have encountered auto-translation only in the case of non-English speech being auto-translated into English - even if I've set the language to Greek. But only in the 'distil' models (like [Systran/faster-distil-whisper-large-v3](https://huggingface.co/Systran/faster-distil-whisper-large-v3)).
> 
> However I don't think it's possible to force the model to parse all sounds as pronunciations in a specific language, regardless of what the language parameter is set to - as evidenced by the Greek example I gave.

Automatic translation occurs between two non-English languages.

**Comment by homelab-00** [comment]
> Automatic translation occurs between two non-English languages.

All right, I'll give my setup a test in this configuration: set the language parameter to Japanese, and feed it a mix of Japanese and Chinese (Mandarin) audio.
