### ISSUE TITLE
PyAudio build issue

### ISSUE THREAD

**Issue by dpresbit** [KoljaB/RealtimeSTT#153]
Had to do the following in order to fix the issue:

`sudo apt-get install portaudio19-dev`

**Comment by loganr0217** [comment]
If on MacOS, you can run the following to fix the issue: 
`brew install portaudio`

**Comment by KoljaB** [comment]
Thanks, I added this information to the Readme.

**Comment by loganr0217** [comment]
Hey, @KoljaB, could you help point me to any issues or ways I can help contribute because I'm trying to gain some familiarity and experience being able to work on and add to existing codebases (and I really like this one because I've been using it for a personal project of mine)?

**Comment by KoljaB** [comment]
> Hey, @KoljaB, could you help point me to any issues or ways I can help contribute because I'm trying to gain some familiarity and experience being able to work on and add to existing codebases (and I really like this one because I've been using it for a personal project of mine)?

Just want to let you know how much i appreciate this and that i am still thinking about what would be suitable issues or features. I will get back to you soon.
