### ISSUE TITLE
Decouple use of wakewords from live transcription

### ISSUE THREAD

**Issue by ekcrisp** [KoljaB/RealtimeSTT#169]
I would like to use this library with my application which does not use wake words. Even importing pvporcupine causes an error that the hardware I'm using is not supported. There is no reason users should be forced to use wake words in order to leverage the live transcription. The functionality in AudioToTextRecorder.transcribe should be split out into its own class that can be used independently from the rest of the library.

**Comment by KoljaB** [comment]
First, let me clarify: this library does not require wake words. They are optional and can be fully disabled. Many users, myself included, run projects without them and this is the first time I’m hearing about pvporcupine installation issues in the context of this library. Third-party dependencies can often cause installation issues, especially in complex open-source projects. I know that problem, so I get how frustrating it can be.

Have you checked the pvporcupine GitHub issues already for a solution? If you share the exact error message here, I’d be happy to help troubleshoot. On your broader point, you’re absolutely right: decoupling AudioToTextRecorder into smaller, single-responsibility classes (like separating wake word functionality from transcription) would improve the library. It’s been on my to-do list for some time but requires significant work. If this feature is critical for you, a fork might be a good starting point. I’m happy to review pull requests!

Thanks for your feedback.

**Comment by ekcrisp** [comment]
Closing this issue as I found a different solution. Like you said, it would be valuable to split up functionality and imports into separate files and classes but not just for code quality. Even if I didn't have import issues I don't want to be forced to bundle libraries I don't need with my software (I am bundling with pyinstaller which goes file by file to pull in dependencies).
