### ISSUE TITLE
new fast models

### ISSUE THREAD

**Issue by francqz31** [KoljaB/RealtimeSTT#18]
there are new fast stt models from nvidia they claim to be better than whisper v3: on here
https://huggingface.co/spaces/hf-audio/open_asr_leaderboard , some of them are really really fast with almost the same accuracy as large whsiper models aka the parakeet family even this one https://huggingface.co/spaces/nvidia/parakeet-rnnt-1.1b is way faster than whisper v3!

**Comment by KoljaB** [comment]
The nvidia stt looks very promising. Word error rate better than whisper and if it's even faster it's for sure is a great candidate. Hope it does all languages well and not only english. I think currently it does not scale to low VRAM systems, Whisper offers tiny model...

pheme looks good, but tbh so do a lot of engines currently. For pure speed for example styletts2 is a really great engine. 6-7x faster than XTTS.

**Comment by tictproject** [comment]
@KoljaB Are you planing to try one of this? Would be awesome to receive faster results since even with Cuda i receive fullSentence event after 3-4 seconds for 3 sentences of text which is not ideal
