### ISSUE TITLE
Whisper as wakeword detection

### ISSUE THREAD

**Issue by olegchomp** [KoljaB/RealtimeSTT#24]
Hi! Is there any easy way to switch wakeword detection from porcupine to whisper?

**Comment by KoljaB** [comment]
Not really, I also really wouldn't recommend that. Whisper would have to nonstop transcribe, which would result in high GPU load  / energy consumption compare to porcupine. Also it can't compete with a wakeword engine in terms of accuracy and detection speed. 

I think for the future switching to [openWakeWord](https://github.com/dscripka/openWakeWord) could be the right thing to do. Need to do some tests before.

**Comment by olegchomp** [comment]
Sadly. As i understand porcupine have only cloud solution for training new words and openwakeword support only EN language.

**Comment by KoljaB** [comment]
Oh, didn't know openwakeword only supports english. That's disappointing, we really need a multilingual, trainable wake word solution. I started with a Whisper wake word implementation first but esp accuracy was rather disappointing. I feel currently there is no easy solution to this problem out there.

**Comment by sailorsale** [comment]
Yes, we do need multilingualism

**Comment by KoljaB** [comment]
OpenWakeword done with [v0.2.0](https://github.com/KoljaB/RealtimeSTT/releases/tag/v0.2.0)
Multilingualism can be done with spelling out the sounds phonetically with underscores separating each part. See OpenWakeword google collab notebook.
