### ISSUE TITLE
listening to m3u8 / rtmp audio

### ISSUE THREAD

**Issue by codenoid** [KoljaB/RealtimeSTT#27]
is it possible to do this?

**Comment by VideoFX** [comment]
I also have a use case here, to analyze the audio coming from these sources. Is it possible to have a real-time live stream feed (such as RTMP) as an input? How would one go about using a remote feed as the input?

**Comment by tychuang1211** [comment]
Just use ffmpeg to pipe your audio.
I am working on a bot to transcribe/translate youtube live stream in realtime.
I use yt-dlp to fetch m3u8 audio chunk and pass it to ffmpeg to process audio into 16-bit PCM chunk, and finally pass the processed chunk to the RealtimeSTT server.
Ends up something like this: 
`python fetch.py [URL] | ffmpeg -f mpegts -i - -c:a pcm_s16le -ac 1 -ar 16000 -f wav - | python send_pcm_to_websocket.py`

**Comment by HoraceDH** [comment]
> 谢谢，我应该关闭它，我已经找到可靠的方法来做到这一点

Hi brother, how did you solve this problem?
