### ISSUE TITLE
browser client example phrases repetition

### ISSUE THREAD

**Issue by GiulioZ94** [KoljaB/RealtimeSTT#31]
I'm encountering slow real-time transcription and occasional repetition issues while using the browser client example (i didn't change anything in the script). It seems that the transcription process is significantly delayed, and certain phrases are repeated multiple times as if the same chunk of text is being transcribed repeatedly.

**Comment by KoljaB** [comment]
You can try upgrading faster-whisper on the server to the latest version with `pip install faster-whisper==1.0.1`, maybe this resolves it. 
Do you have these issues only with the browserclient example or does it happen with other tests too?
What does `print(torch.cuda.is_available())` on the server show? 
Which OS and python version are you running?

**Comment by GiulioZ94** [comment]
Thanks, my faster whisper version was 0.1.0. Now it works very well
