### ISSUE TITLE
Scipy missing from requirements.txt?

### ISSUE THREAD

**Issue by DanMakingWithAI** [KoljaB/RealtimeSTT#39]
I installed RealtimeSTT via `pip` (in a new and otherwise empty virtual environment) and tried to run a simple test script with `from RealtimeSTT import AudioToTextRecorder` as the only import. I then got a module missing error for `scipy`. I installed it via `pip` and then everyting worked fine (via CPU, as noted in the readme).

Does `scipy` need adding to the requirements.txt files?

**Comment by KoljaB** [comment]
Yep, was missing. Added it, thank you.
