### ISSUE TITLE
Provide ID for data & transcribtion

### ISSUE THREAD

**Issue by Stefan-Kosker** [KoljaB/RealtimeSTT#45]
Especially for slow devices (for example cpu) there is the problem of speech going on while transcription is happening. I want to add a "listen again" function using on_recorded_chunk saving the chunk and making this file available for listening on frontend. I want to map transcription and data later on since transcription is async. To be able to achieve this, I have to have the queue.

Can you please add arguments "transcription_id" as argument on_recorded_chunk and also recorder.text?

Thank you.

**Comment by Stefan-Kosker** [comment]
Obviously, I can trust first come first serve in a queue. But since working with MQTT Brokers, I don't trust queues and first come first serves :D

**Comment by KoljaB** [comment]
I don't think this is necessary. This lib does not really allow transcriptions "overtaking" another so every text received from .text() method or on_transcription_finished callback should come in chronological order. Also adding return parameters to .text() breaks current api.

**Comment by Stefan-Kosker** [comment]
I understand. Library is not fully async. This makes sense from this point of view. Thank you mate.
