### ISSUE TITLE
TTS

### ISSUE THREAD

**Issue by oijoijcoiejoijce** [KoljaB/RealtimeSTT#5]
Impressive work - do you have any insight on applying the same methodology for TTS?

**Comment by KoljaB** [comment]
I have [this](https://github.com/KoljaB/RealtimeTTS) library for TTS, which is very fast imho. I'm working on coqui Integration there currently. Especially their new XTTS model is quite impressing for realtime TTS.

**Comment by williemccool** [comment]
How do we use them together?

**Comment by KoljaB** [comment]
There are some test files that show how to use both libraries together, like translator.py or openai_voice_interface.py. I copied some of these into both libs' test folder, I'm sorry that this caused confusion.
