### ISSUE TITLE
the on_realtime_transcription_update text issue 

### ISSUE THREAD

**Issue by jacobtang** [KoljaB/RealtimeSTT#69]
Hi,@KoljaB
I use the on_realtime_transcription_update(also try the on_realtime_transcription_stabilized) text,send to the web client,but it always show the pre text word.
Is there other method that can avoid show the repeated pre words?Thanks!
![image](https://github.com/KoljaB/RealtimeSTT/assets/15025269/b2d667ee-6463-4165-ac11-ada3f1633f66)
I try to implement live transcription function similar to Zoom Meeting in the product.

**Comment by KoljaB** [comment]
No, that ist due to the way Whisper works and how it therefore is implemented. You'd need to program this on top of that.

**Comment by jacobtang** [comment]
Ok,thanks a  lot!
I use the process_text callback data, it costs about 3s,is it normal?how should I reduce the time cost?
use the recorder_config,and recorder.feed_audio(audio_chunk) method in GPU env.

`
def recorder_thread():
    global recorder, recorder_ready
    print("Initializing RealtimeSTT")
    recorder = AudioToTextRecorder(**recorder_config)
    print("RealtimeSTT initialized")
    recorder_ready.set()
    while True:
        recorder.text(process_text)

if __name__ == '__main__':
    print("Starting server, please wait...")
    recorder_ready = threading.Event()
    recorder_config = {
        'spinner': False,
        'use_microphone': False,
        'model': 'distil-small.en',
        'language': 'en',
        'silero_sensitivity': 0.4,
        'webrtc_sensitivity': 2,
        'post_speech_silence_duration': 0.4,
        'min_length_of_recording': 0,
        'min_gap_between_recordings': 0,
        'enable_realtime_transcription': False,
        'realtime_processing_pause': 0.2,
        'realtime_model_type': 'distil-small.en',
        'beam_size_realtime': 1,
        'on_realtime_transcription_update': text_detected,
    }
`

**Comment by jacobtang** [comment]
Ok,thanks a lot!
I use the process_text callback data, it costs about 3s,is it normal?how should I reduce the time cost?
use the recorder_config,and recorder.feed_audio(audio_chunk) method in GPU env.

def recorder_thread():
    global recorder, recorder_ready
    print("Initializing RealtimeSTT")
    recorder = AudioToTextRecorder(**recorder_config)
    print("RealtimeSTT initialized")
    recorder_ready.set()
    while True:
        recorder.text(process_text)

if __name__ == '__main__':
    print("Starting server, please wait...")
    recorder_ready = threading.Event()
    recorder_config = {
        'spinner': False,
        'use_microphone': False,
        'model': 'distil-small.en',
        'language': 'en',
        'silero_sensitivity': 0.4,
        'webrtc_sensitivity': 2,
        'post_speech_silence_duration': 0.4,
        'min_length_of_recording': 0,
        'min_gap_between_recordings': 0,
        'enable_realtime_transcription': False,
        'realtime_processing_pause': 0.2,
        'realtime_model_type': 'distil-small.en',
        'beam_size_realtime': 1,
        'on_realtime_transcription_update': text_detected,
    }

**Comment by jacobtang** [comment]
Ok,thanks a lot!
I use the process_text callback data, it costs about 3s to get the text data, is it normal? how should I reduce the time cost?
use the recorder_config,and recorder.feed_audio(audio_chunk) method in GPU env.

**Comment by jacobtang** [comment]
Ok,thanks a lot!
I use the process_text callback data, it costs about 3s to get the text data, is it normal? how should I reduce the time cost?
use the recorder_config,and recorder.feed_audio(audio_chunk) method in GPU env.
![image](https://github.com/KoljaB/RealtimeSTT/assets/15025269/f4c38bb7-c7c0-462d-8c3c-49b81ae38967)

**Comment by KoljaB** [comment]
Absolutely not normal. Even with largest model or on CPU transcription time should be way below 1s.
I have no real idea, why this happens. 
Can you please try another model, like small.en or medium? Also a separated test with only faster_whisper library could tell us if it's the transcription or maybe something related to the VAD models.
