### ISSUE TITLE
Can we dynamiclly detect the language code?

### ISSUE THREAD

**Issue by ahmed-troido** [KoljaB/RealtimeSTT#98]
I want to get the language code that the user speaks (en, de ..etc),
Can we detect the language code after the user speaks?

**Comment by KoljaB** [comment]
I see this can be helpful. Requires some changes to the code though. I try to come up with something soon that allows that.

**Comment by KoljaB** [comment]
Please check [new version v0.2.3](https://github.com/KoljaB/RealtimeSTT/releases/tag/v0.2.3) with support for language detection. Also please look [at realtimestt_test.py](https://github.com/KoljaB/RealtimeSTT/blob/master/tests/realtimestt_test.py) for an implementation example.

**Comment by ahmed-troido** [comment]
thank you so much for this feature.
